=== Darkwolf69/FE019W_XMLGyak/XMLTaskFE019W/XMLSchemaFE019W.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://iit.uni-miskolc.hu"
	xmlns="http://iit.uni-miskolc.hu" elementFormDefault="qualified">
	
	<xs:element name="pizzazo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="megrendelo" />
				<xs:element name="futar" />
				<xs:element name="pizza" />
				<xs:element name="szakacs" />
				<xs:element name="belepokartya" />
				<xs:element name="osszetevo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="megrendelo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" />
				<xs:element name="telefonszam" />
				<xs:element name="lakcim" type="cimkomplex" />
			</xs:sequence>
			<xs:attribute name="mkod" type="xs:integer" use="required" />
		</xs:complexType>
		<xs:key name="mkod">
			<xs:selector xpath="./megrendelo"/>
			<xs:field xpath="@mkod"/>
		</xs:key>
		<xs:keyref name="mkodref" refer="mkod">
			<xs:selector xpath="./pizza"/>
			<xs:field xpath="@mkod"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="futar">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="telefonszam" />
				<xs:element name="nev" />
				<xs:element name="eletkor" type="xs:integer"/>
				<xs:element name="robogoTipus" />
			</xs:sequence>
			<xs:attribute name="fkod" type="xs:integer" use="required" />
		</xs:complexType>
		<xs:key name="fkod">
			<xs:selector xpath="./futar"/>
			<xs:field xpath="@fkod"/>
		</xs:key>
		<xs:keyref name="fkodref" refer="fkod">
			<xs:selector xpath="./pizza"/>
			<xs:field xpath="@fkod"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="pizza">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fajta" />
				<xs:element name="meret" />
				<xs:element name="ar" type="xs:integer"/>
			</xs:sequence>
			<xs:attribute name="pkod" type="xs:integer" use="required" />
		</xs:complexType>
		<xs:key name="pkod">
			<xs:selector xpath="./pizza"/>
			<xs:field xpath="@pkod"/>
		</xs:key>
		<xs:keyref name="pkodref" refer="pkod">
			<xs:selector xpath="./szukseges"/>
			<xs:field xpath="@pkod"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="szakacs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" />
				<xs:element name="eletkor" />
				<xs:element name="kepesites" />
			</xs:sequence>
			<xs:attribute name="szkod" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="belepokartya">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="azonosito" type="xs:integer"/>
				<xs:element name="kiadasEve" />
				<xs:element name="lejaratEve" />
			</xs:sequence>
			<xs:attribute name="bkod" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="osszetevo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="elelmiszer" type="elelemkomplex"/>
			</xs:sequence>
			<xs:attribute name="okod" type="xs:integer" use="required" />
		</xs:complexType>
		<xs:key name="okod">
			<xs:selector xpath="./osszetevo"/>
			<xs:field xpath="@okod"/>
		</xs:key>
		<xs:keyref name="okodref" refer="okod">
			<xs:selector xpath="./szukseges"/>
			<xs:field xpath="@okod"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="szukseges">
		<xs:complexType>
			<xs:attribute name="pkod" type="xs:integer" use="required"/>
			<xs:attribute name="okod" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="cimkomplex">
		<xs:sequence>
			<xs:element name="iranyitoszam" />
			<xs:element name="varos" />
			<xs:element name="utca" />
			<xs:element name="hazszam" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="elelemkomplex">
		<xs:sequence>
			<xs:element name="nev" />
			<xs:element name="tipus" />
			<xs:element name="tomeg" />
			<xs:element name="lejarat" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Darkwolf69/FE019W_XMLGyak/XMLTaskFE019W/XMLFE019W.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizzazo
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://iit.uni-miskolc.hu XMLSchemaFE019W.xsd">
	<megrendelo mkod="1">
		<nev>Ehes Elemer</nev>
		<telefonszam>301111111</telefonszam>
		<lakcim>
			<iranyitoszam>2500</iranyitoszam>
			<varos>Kisfalva</varos>
			<utca>Kis utca</utca>
			<hazszam>6</hazszam>
		</lakcim>
	</megrendelo>
	<megrendelo mkod="2">
		<nev>Kajas Andras</nev>
		<telefonszam>302222222</telefonszam>
		<lakcim>
			<iranyitoszam>2600</iranyitoszam>
			<varos>Kozepesfalva</varos>
			<utca>Kozepes utca</utca>
			<hazszam>24</hazszam>
		</lakcim>
	</megrendelo>
	<megrendelo mkod="3">
		<nev>Husos Hugo</nev>
		<telefonszam>706666666</telefonszam>
		<lakcim>
			<iranyitoszam>2700</iranyitoszam>
			<varos>Nagyfalva</varos>
			<utca>Nagy utca</utca>
			<hazszam>8</hazszam>
		</lakcim>
	</megrendelo>
	<futar fkod="1">
		<telefonszam>205555555</telefonszam>
		<nev>Sebes Soma</nev>
		<eletkor>20</eletkor>
		<robogoTipus>Babetta</robogoTipus>
	</futar>
	<futar fkod="2">
		<telefonszam>308888888</telefonszam>
		<nev>Gyors Gyula</nev>
		<eletkor>22</eletkor>
		<robogoTipus>Simson</robogoTipus>
	</futar>
	<pizza pkod="1">
		<fajta>Margherita</fajta>
		<meret>20</meret>
		<ar>2000</ar>
	</pizza>
	<pizza pkod="2">
		<fajta>Magyaros</fajta>
		<meret>30</meret>
		<ar>3000</ar>
	</pizza>
	<pizza pkod="3">
		<fajta>Bolognese</fajta>
		<meret>25</meret>
		<ar>2500</ar>
	</pizza>
	<pizza pkod="4">
		<fajta>Prosciutto</fajta>
		<meret>20</meret>
		<ar>2800</ar>
	</pizza>
	<szakacs szkod="1">
		<nev></nev>
		<eletkor></eletkor>
		<kepesites></kepesites>
	</szakacs>
	<szakacs szkod="2">
		<nev>Sütő Samu</nev>
		<eletkor>30</eletkor>
		<kepesites>szakács</kepesites>
	</szakacs>
	<belepokartya bkod="1">
		<azonosito>24953</azonosito>
		<kiadasEve>2020</kiadasEve>
		<lejaratEve>2025</lejaratEve>
	</belepokartya>
	<belepokartya bkod="2">
		<azonosito>67159</azonosito>
		<kiadasEve>2019</kiadasEve>
		<lejaratEve>2024</lejaratEve>
	</belepokartya>
	<osszetevo okod="1">
		<elelmiszer>
			<nev>BL 55</nev>
			<tipus>gabona</tipus>
			<tomeg>1000</tomeg>	
			<lejarat>2022.02.16</lejarat>
		</elelmiszer>
	</osszetevo>
	<osszetevo okod="2">
		<elelmiszer>
			<nev>csirkemell</nev>
			<tipus>hús</tipus>
			<tomeg>300</tomeg>	
			<lejarat>2021.12.09</lejarat>
		</elelmiszer>
	</osszetevo>
	<osszetevo okod="3">
		<elelmiszer>
			<nev>paprika</nev>
			<tipus>zöldség</tipus>
			<tomeg>100</tomeg>	
			<lejarat>2021.12.19</lejarat>
		</elelmiszer>
	</osszetevo>
	<osszetevo okod="4">
		<elelmiszer>
			<nev>kukorica</nev>
			<tipus>gabona</tipus>
			<tomeg>200</tomeg>	
			<lejarat>2022.03.26</lejarat>
		</elelmiszer>
	</osszetevo>
	<osszetevo okod="5">
		<elelmiszer>
			<nev>darálthús</nev>
			<tipus>hús</tipus>
			<tomeg>500</tomeg>	
			<lejarat>2021.12.08</lejarat>
		</elelmiszer>
	</osszetevo>
	<osszetevo okod="6">
		<elelmiszer>
			<nev>bazsalikom</nev>
			<tipus>fűszer</tipus>
			<tomeg>50</tomeg>	
			<lejarat>2023.06.04</lejarat>
		</elelmiszer>
	</osszetevo>
</pizzazo>
